exports.REQUEST_ARTICLES = 'REQUEST_ARTICLES';
exports.ARTICLES_SUCCESS = 'ARTICLES_SUCCESS';
exports.ARTICLES_FAILURE = 'ARTICLES_FAILURE';

exports.ADD_ARTICLE = 'ADD_ARTICLE';
exports.ADD_ARTICLES = 'ADD_ARTICLES';
exports.UPDATE_ARTICLE = 'UPDATE_ARTICLE';
exports.REMOVE_ARTICLE = 'REMOVE_ARTICLE';
